const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.forms = require("./form.model")(mongoose)
db.tokens = require("./token.model")(mongoose);
db.answers = require("./answer.model")(mongoose)
db.questions = require("./question.model")(mongoose)
db.comments = require("./comment.model")(mongoose)
db.threads = require("./thread.model")(mongoose)
module.exports = db;
